model:
  name: 'openai/whisper-base' # any 'openai/whisper-...'
  batch_size: 8
  lr: 0.00002
  num_labels: 2
  num_epochs: 1
  device: 'cuda'
  sampling_rate: 16000

loss:
  name: 'ce' # ['ce', 'focal']
  gamma: 2
  know_weights: false
  w1: ...
  w2: ...
